# Generated by Django 3.0.8 on 2020-08-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=250)),
                ('CommonName', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('ScientificName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Minerals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalNutriments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vitamins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Foos_has_Minerals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.FloatField()),
                ('Food_idFood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Food')),
                ('Minerals_idMinerals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Minerals')),
            ],
        ),
        migrations.CreateModel(
            name='Food_has_Vitamins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.FloatField()),
                ('Food_idFood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Food')),
                ('Vitamins_idVitamins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Vitamins')),
            ],
        ),
        migrations.CreateModel(
            name='Food_has_PrincipalNutriments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.FloatField()),
                ('Food_idFood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Food')),
                ('PrincipalNutriments_idPrincipalNutriments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.PrincipalNutriments')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='Group_idGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Group'),
        ),
    ]
