# Generated by Django 3.0.8 on 2020-08-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPlatopedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foos_has_Minerals',
            new_name='Food_has_Minerals',
        ),
    ]
