# Generated by Django 3.0.8 on 2020-08-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPlatopedia', '0002_auto_20200805_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value_Minerals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Value_PrincipalNutriments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Value_Vitamins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='food_has_principalnutriments',
            name='Food_idFood',
        ),
        migrations.RemoveField(
            model_name='food_has_principalnutriments',
            name='PrincipalNutriments_idPrincipalNutriments',
        ),
        migrations.RemoveField(
            model_name='food_has_vitamins',
            name='Food_idFood',
        ),
        migrations.RemoveField(
            model_name='food_has_vitamins',
            name='Vitamins_idVitamins',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='CommonName',
            new_name='commonName',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Group_idGroup',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='ScientificName',
            new_name='scientificName',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='principalnutriments',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vitamins',
            old_name='Name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Food_has_Minerals',
        ),
        migrations.DeleteModel(
            name='Food_has_PrincipalNutriments',
        ),
        migrations.DeleteModel(
            name='Food_has_Vitamins',
        ),
        migrations.AddField(
            model_name='value_vitamins',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Food'),
        ),
        migrations.AddField(
            model_name='value_vitamins',
            name='vitamins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Vitamins'),
        ),
        migrations.AddField(
            model_name='value_principalnutriments',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Food'),
        ),
        migrations.AddField(
            model_name='value_principalnutriments',
            name='principalnutriments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.PrincipalNutriments'),
        ),
        migrations.AddField(
            model_name='value_minerals',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Food'),
        ),
        migrations.AddField(
            model_name='value_minerals',
            name='minerals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlatopedia.Minerals'),
        ),
        migrations.AddField(
            model_name='minerals',
            name='value_min',
            field=models.ManyToManyField(through='appPlatopedia.Value_Minerals', to='appPlatopedia.Food'),
        ),
        migrations.AddField(
            model_name='principalnutriments',
            name='value_pri',
            field=models.ManyToManyField(through='appPlatopedia.Value_PrincipalNutriments', to='appPlatopedia.Food'),
        ),
        migrations.AddField(
            model_name='vitamins',
            name='value_vit',
            field=models.ManyToManyField(through='appPlatopedia.Value_Vitamins', to='appPlatopedia.Food'),
        ),
    ]
