# Generated by Django 3.0.8 on 2020-08-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPlatopedia', '0003_auto_20200805_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='commonName',
            new_name='common_name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='scientificName',
            new_name='scientificname',
        ),
    ]
