# Generated by Django 3.0.8 on 2020-08-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPlatopedia', '0004_auto_20200805_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minerals',
            old_name='Name',
            new_name='name',
        ),
    ]
